### ISSUE TITLE
Add Paralus Logo On Login Screen

### ISSUE THREAD

**Issue by techmaharaj** [paralus/dashboard#110]
The feature request is to add the Paralus logo on the login screen above the username and password fields.

This logo can be configurable during installation via the yaml configuration file so the user can replace the logo with theirs instead of using the Paralus's default logo (or remove it alltogether)

It will not only make the login page look good, but also professional.

**Comment by meain** [comment]
It would be a good addition in the forgot password screen as well.

**Comment by developer-irfan** [comment]
@techmaharaj assign me this task so i add the logo in login screen.

**Comment by meain** [comment]
@developer-irfan Thanks for looking into it.
