### ISSUE TITLE
Cluster status is always showing as green

### ISSUE THREAD

**Issue by akshay196** [paralus/dashboard#181]
### Expected vs actual behavior

Imported clusters are always showing status as connected and health (green status dot) even if the cluster is unreachable.

![Screenshot from 2023-04-15 11-55-12](https://user-images.githubusercontent.com/16691314/232190452-40dce52a-9539-4eed-860c-5c37e6a01fc8.png)

Expected: The status should be updated based on Paralus controller and cluster connectivity.

### Steps to reproduce the bug

1. Import the cluster to Paralus
2. Disconnect the cluster
3. Status indicator is still green

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

Yes

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

- 

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [X] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X] I'm using the latest version of the project.

**Comment by niravparikh05** [comment]
So, this represents whether cluster is imported. Until then it would be Pending, once bootstrap is applied to target cluster and relay-agent registers itself to paralus core it will update to Success - Imported. If we need to check whether the cluster connection is healthy or unhealthy it can be found in cluster listing page. Refer below screenshot. 

Closing this as complete.

![image](https://github.com/paralus/dashboard/assets/52062717/4183a98e-a323-4dd0-823d-df0f4e73e6ce)
